server:
  port: 8002
spring:
  application:
    name: cloud-provider-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.msr.cloudv2.entity
eureka:
  instance:
    #访问路径可以显示ip
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 20
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 10
    instance-id: paymeny-service-8002
  #    ip-address:
#    prefer-ip-address: true
  client:
    service-url:
#      单机版
#      defaultZone: http://localhost:8002/eureka/
#      集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
